Updated issuer init implementation and added wallet ui

diff --git a/components/issuer-api/templates/deployment.yaml b/components/issuer-api/templates/deployment.yaml
--- a/components/issuer-api/templates/deployment.yaml
+++ b/components/issuer-api/templates/deployment.yaml
@@ -38,141 +38,176 @@ spec:
       - name: {{ template "app.chartname" . }}
         image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ default .Chart.AppVersion .Values.image.tag }}"
         imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
-        {{- if and .Values.ingress.tls (gt (len .Values.ingress.tls) 0) }}
         command: 
-          - /bin/sh
+          - /bin/bash
         args:
           - -c
           - |
+            set -x
+            
+            {{- if and .Values.ingress.tls (gt (len .Values.ingress.tls) 0) }}
             for f in /opt/{{ .Values.name }}/certs/*.crt; do 
               echo "Adding certificate $f to keystore"
               certname=$(echo $(basename $f) | sed 's|.crt||g' )
               keytool -import -trustcacerts -noprompt -storepass changeit -alias $(basename $f) -file $f -keystore ${JAVA_HOME}/lib/security/cacerts
             done
-            echo "Starting VC Issuer API" 
-            /app/bin/waltid-ssikit serve -b 0.0.0.0 &
-            #JAVA_OPTS="-Dorg.slf4j.simpleLogger.defaultLogLevel=DEBUG" /app/bin/waltid-ssikit serve -b 0.0.0.0
-            if [ -n  "{{ .Values.config.registry.service.name }}" ]; then
-              while true; do 
-                # give some time for wallet to start and be ready
-                  echo "Waiting 5 seconds before trying..."
-                  sleep 10
-                  vault_url='http://{{ .Values.config.vault.service.name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.config.vault.service.http.Port }}'
-                  url='http://{{ .Values.config.registry.service.name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.config.registry.service.http.Port }}/wallet-api/registry'
-                  echo $url
-                  echo $vault_url
-                   # get DID from the wallet
-                  RESPONSE=$(curl -s -w "HTTPSTATUS:%{http_code}" -X 'GET' \
-                  "$url")
-                   # get key name
-                  RESPONSEKEY=$(curl -s -w "HTTPSTATUS:%{http_code}" -X 'LIST' \
-                  --header "X-Vault-Token: {{ .Values.config.vault.service.tesToken }}" \
-                  "$vault_url/v1/transit/keys")
-                  echo "this is the response of the key $RESPONSEKEY"
-                  BODY=$(echo "$RESPONSE" | sed -e 's/HTTPSTATUS:.*//')
-                  STATUS_CODE=$(echo "$RESPONSE" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
-                  BODYKEY=$(echo "$RESPONSEKEY" | sed -e 's/HTTPSTATUS:.*//')
-                  STATUS_CODE_KEY=$(echo "$RESPONSEKEY" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
-                  KEYS_NAMES=$(echo "$BODYKEY" | awk -F'"keys":\\[|\\]' '{print $2}')
-                  RESULTKEY=$(echo "$KEYS_NAMES" | awk -F',' '
-                  {
-                    for (i = 1; i <= NF; i++) {
-                      gsub(/"| /, "", $i)  # Remove quotes and spaces
-                      if ($i != "key1" && $i != "key2" && $i != "key3") {
-                        print $i
-                      }
-                    }
-                  }')
-                  echo "key status ID $STATUS_CODE_KEY"
-                  echo "key ID $RESULTKEY"
-                  echo "this is the registry id $RESPONSE"
-                  if [ "$STATUS_CODE" -eq 200 ] && [ "$STATUS_CODE_KEY" -eq 200 ] && [ -n "$RESULTKEY" ] && [ -n "$BODY" ]; then
-                    # change the key to exportable 
-                    updateKeyStatus=$(curl -s -o /dev/null -w "%{http_code}"\
-                    --header "X-Vault-Token: root" \
-                    --request POST \
-                    --data '{"exportable":true}' \
-                    "$vault_url/v1/transit/keys/$RESULTKEY/config")
-                    echo "Received 200 OK from the API."
-                    echo $BODY
-                    did=$( echo "$BODY" | awk -F'"' '{print $2}')
-                    registryId=$(echo $BODY | awk -F':' '{gsub(/[^a-zA-Z0-9-]/, "", $NF); print $NF}')
-                    didFile=$(curl -s  -X 'GET' \
-                    "$url/$registryId/did.json")
-                    echo $registryId
-                    echo $didFile
-                    echo "code $updateKeyStatus"
-                    if [ "$updateKeyStatus" -eq 200 ]; then
-                      KEY=$(curl -s -w "HTTPSTATUS:%{http_code}" -X 'GET' \
-                      --header "X-Vault-Token: {{ .Values.config.vault.service.tesToken }}" \
-                      "$vault_url/v1/transit/export/signing-key/$RESULTKEY/1")
-                      KEY_CONTENT=$(echo "$KEY" | sed -e 's/HTTPSTATUS:.*//')
-                      GET_KEY_CODE=$(echo "$KEY" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
-                      COMBINED_KEY=$(echo "$KEY_CONTENT" | awk -F'"keys":\\{"1":"|"}' '{print $2}')
-                      if [ "$GET_KEY_CODE" -eq 200 ]; then
-                        echo "$COMBINED_KEY" | base64 -d > combined_key.bin
-                        # Extract the private key (first 32 bytes)
-                        dd if=combined_key.bin of=private_key.bin bs=1 count=32 2>/dev/null
+            {{- end }}
 
-                        # Extract the public key (last 32 bytes)
-                        dd if=combined_key.bin of=public_key.bin bs=1 skip=32 count=32 2>/dev/null
+            echo "Starting SSIKit" 
+            # JAVA_OPTS="-Dorg.slf4j.simpleLogger.defaultLogLevel=DEBUG" bin/waltid-ssikit serve -b 0.0.0.0 &
+            /app/bin/waltid-ssikit serve -b 0.0.0.0 #&
 
-                        # Encode the extracted keys back to Base64 for readability
-                        PRIVATE_KEY_BASE64=$(base64 < private_key.bin)
-                        PUBLIC_KEY_BASE64=$(base64 < public_key.bin)
-                        # Clean up binary files
-                        rm -f combined_key.bin private_key.bin public_key.bin
-                        break
-                        
-                      fi
-                    fi
-                  fi
-              done
-              # Import the key to the service
-              kid=$(echo "$UPDATED_DID" | awk -F'"' '/"id": "did:web/ {print $4}')
+            # # give some time for wallet to start and be ready
+            # sleep 40
+            
+            # body=""
+            # code=0
+            
+            # #################################################
+            # # Get DID document
+            # #################################################
+            # response=$(curl -s -w "|%{http_code}" \
+            #   http://{{ .Values.config.issuer.did | replace "did:web:" "" | replace ":" "/" }}/did.json)
+            # body=$(echo $response | awk -F '|' '{print $1}')
+            # code=$(echo $response | awk -F '|' '{print $2}')
+            # if [ $code -eq 200 ]; then
+            #   echo "Got DID document"
+            # else
+            #   echo "Bad Request"
+            #   exit 1
+            # fi
+            
+            # #################################################
+            # # Get Key Id
+            # #################################################
+            # kid=$(echo $body | grep -m1 -oE '"kid":"[^"]+"' | awk -F '":"' '{gsub(/"/,"",$2); print $2}')
+            # if [ -z "$kid" ]; then
+            #   kid=$(echo $body | grep -oE '{{ .Values.config.issuer.did }}#[^"]+' | head -1 | awk -F '#' '{print $2}')
               
-              UPDATED_DID=$(echo "$didFile" | awk -v kid_val="$RESULTKEY" '
-                            BEGIN { RS=""; FS=""; }
-                            {
-                                # Match the "publicKeyJwk" block
-                                sub(/"publicKeyJwk": *\{/, "&\n\"kid\": \"" kid_val "\",");
-                                print;
-                            }
-                            ')
-              kid=$(echo "$UPDATED_DID" | awk -F'"' '
-              /"verificationMethod"/ { in_verification_method = 1 }
-              in_verification_method && /"id":/ {                 
-                  for (i = 1; i <= NF; i++)                       
-                      if ($i ~ /^did:web/ && $i ~ /#/) {           
-                          print $i
-                          in_verification_method = 0   
-                          exit           
-                      }
-              }')
-              echo "final did $UPDATED_DID "
-              sleep 5 
-              curl -X 'POST' \
-              'http://0.0.0.0:7002/keys/import' \
-              -H 'accept: application/json' \
-              -H 'Content-Type: application/json' \
-              -d "{
-                \"kty\": \"OKP\",
-                \"use\": \"sig\",
-                \"crv\": \"Ed25519\",
-                \"kid\": \"$kid\",
-                \"d\": \"$PRIVATE_KEY_BASE64\",
-                \"x\": \"$PUBLIC_KEY_BASE64\",
-                \"alg\": \"EdDSA\"
-                  }" 
-              echo $UPDATED_DID > /app/data/did/created/did%3Aweb%3Adataspace4health.local%3Awallet%3Aapi%3Awallet-api%3Aregistry%3Antt &
-              while true;do sleep 3600;done
-            fi
-          - | 
-            echo "process completed"
+            #   body1=$(echo $body | awk -F '"publicKeyJwk":\\{' '{print $1}')
+            #   body2=$(echo $body | awk -F '"publicKeyJwk":\\{' '{print $2}')
 
+            #   body=$(printf '%s"publicKeyJwk":{"kid":"%s",%s' $body1 $kid $body2)
+            # fi
 
-          {{- end }}
-      
+            # #################################################
+            # # Save DID document
+            # #################################################
+            # mkdir -p /app/data/did/created
+            # echo $body > /app/data/did/created/{{ .Values.config.issuer.did | replace ":" "%3A" }}
+
+            # #################################################
+            # # Get List of Keys from Vault
+            # #################################################
+            # response=$(curl -s -w "|%{http_code}" -X LIST \
+            #   -H "X-Vault-Token: {{ .Values.config.vault.token }}" \
+            #   "{{ .Values.config.vault.url }}/v1/transit/keys")
+            # body=$(echo $response | awk -F '|' '{print $1}')
+            # code=$(echo $response | awk -F '|' '{print $2}')
+            # if [ $code -eq 200 ]; then
+            #   echo "Got Vault keys"
+            # else
+            #   echo "Bad Request"
+            #   exit 1
+            # fi
+
+            # keys=($(echo $body | grep -m1 -oE '"keys":\[[^\]+\]' | awk -F '"keys":' '{gsub(/\[/,"",$2); gsub(/\]/,"",$2); gsub(/"/,"",$2); gsub(/,/," ",$2); print $2}'))
+            # for keyId in "${keys[@]}"
+            # do
+            #   if [ "$keyId" = "key1" ] || [ "$keyId" = "key2" ] || [ "$keyId" = "key3" ]; then
+            #     continue
+            #   fi
+              
+            #   #################################################
+            #   # Set key as exportable
+            #   #################################################
+            #   response=$(curl -s -w "|%{http_code}" -X POST \
+            #     -H "X-Vault-Token: {{ .Values.config.vault.token }}" \
+            #     -d '{"exportable":true}' \
+            #     "{{ .Values.config.vault.url }}/v1/transit/keys/$keyId/config")
+            #   body=$(echo $response | awk -F '|' '{print $1}')
+            #   code=$(echo $response | awk -F '|' '{print $2}')
+            #   if [ $code -eq 200 ]; then
+            #     echo "Key $keyId set as exportable"
+            #   else
+            #     echo "Bad Request"
+            #     exit 1
+            #   fi
+              
+            #   #################################################
+            #   # Export key
+            #   #################################################
+            #   response=$(curl -s -w "|%{http_code}" -X GET \
+            #     -H "X-Vault-Token: {{ .Values.config.vault.token }}" \
+            #     "{{ .Values.config.vault.url }}/v1/transit/export/signing-key/$keyId/1")
+            #   body=$(echo $response | awk -F '|' '{print $1}')
+            #   code=$(echo $response | awk -F '|' '{print $2}')
+            #   if [ $code -eq 200 ]; then
+            #     echo "Key $keyId exported"
+            #   else
+            #     echo "Bad Request"
+            #     exit 1
+            #   fi
+
+            #   key=$(echo $body | grep -m1 -oE '"1":"[^"]+"' | awk -F '":"' '{gsub(/"/,"",$2); print $2}')
+
+            #   #################################################
+            #   # Extract public and private keys
+            #   #################################################
+            #   echo "$key" | base64 -d > /tmp/combined_key.bin
+            #   # Extract the private key (first 32 bytes)
+            #   dd if=/tmp/combined_key.bin of=/tmp/private_key.bin bs=1 count=32 2>/dev/null
+
+            #   # Extract the public key (last 32 bytes)
+            #   dd if=/tmp/combined_key.bin of=/tmp/public_key.bin bs=1 skip=32 count=32 2>/dev/null
+
+            #   # Encode the extracted keys back to Base64 for readability
+            #   PRIVATE_KEY_BASE64=$(base64 < /tmp/private_key.bin)
+            #   PUBLIC_KEY_BASE64=$(base64 < /tmp/public_key.bin)
+            #   # Clean up binary files
+            #   rm -f /tmp/combined_key.bin /tmp/private_key.bin /tmp/public_key.bin
+
+            #   #################################################
+            #   # Import key
+            #   #################################################
+            #   response=$(curl -s -w "|%{http_code}" -X POST \
+            #     -H 'accept: application/json' \
+            #     -H 'Content-Type: application/json' \
+            #     -d "{
+            #       \"kty\": \"OKP\",
+            #       \"use\": \"sig\",
+            #       \"crv\": \"Ed25519\",
+            #       \"kid\": \"$keyId\",
+            #       \"d\": \"$PRIVATE_KEY_BASE64\",
+            #       \"x\": \"$PUBLIC_KEY_BASE64\",
+            #       \"alg\": \"EdDSA\"
+            #     }" \
+            #     "http://0.0.0.0:7002/keys/import")
+            #   body=$(echo $response | awk -F '|' '{print $1}')
+            #   code=$(echo $response | awk -F '|' '{print $2}')
+            #   if [ $code -eq 200 ]; then
+            #     echo "Key $keyId imported"
+            #   else
+            #     echo "Bad Request"
+            #     exit 1
+            #   fi
+
+            #   #################################################
+            #   # Set key as not exportable
+            #   #################################################
+            #   response=$(curl -s -w "|%{http_code}" -X POST \
+            #     -H "X-Vault-Token: {{ .Values.config.vault.token }}" \
+            #     -d '{"exportable":false}' \
+            #     "{{ .Values.config.vault.url }}/v1/transit/keys/$keyId/config")
+            #   body=$(echo $response | awk -F '|' '{print $1}')
+            #   code=$(echo $response | awk -F '|' '{print $2}')
+            #   if [ $code -eq 200 ]; then
+            #     echo "Key $keyId set as not exportable"
+            #   else
+            #     echo "Bad Request"
+            #     exit 1
+            #   fi
+            # done
         {{- if .Values.useSecretRef }}
         envFrom:
           - secretRef:
@@ -183,9 +218,6 @@ spec:
               name: {{ .Values.configMapName }}
         {{- else }}
         env:
-        #  - name: JAVA_OPTS
-        #    value: >
-        #     "-Dorg.slf4j.simpleLogger.defaultLogLevel=DEBUG"
         {{- end }}
 
         {{- if .Values.secretEnv }}
@@ -196,7 +228,6 @@ spec:
                 name: "{{ $value.name }}"
           {{- end }}
         {{- end }}
-
 {{- if .Values.extraVars }}
 {{ toYaml .Values.extraVars | indent 8 }}
 {{- end }}
@@ -205,12 +236,13 @@ spec:
           - name: monitoring
             containerPort: {{ .Values.metrics.port }}
         {{- end }}
-          - name: http
-            containerPort: {{ .Values.config.http.port }}
+        {{- if .Values.config.ports }}
+{{ toYaml .Values.config.ports | indent 8 }}
+        {{- end }}
         readinessProbe:
           httpGet:
             path: /health
-            port: {{ .Values.config.http.port }}
+            port: 7000
           initialDelaySeconds: 5
           periodSeconds: 5
           successThreshold: 2
@@ -221,7 +253,11 @@ spec:
             mountPath: "/app/config/signatory.conf"
             subPath: "signatory.conf"
             readOnly: true
+          - mountPath: "/app/data/credential-store"
+            name: data-volume
           - mountPath: "/app/data/revocation"
+            name: data-volume
+          - mountPath: "/app/data/vc"
             name: data-volume
           {{ $name := .Values.name }}
           {{- range .Values.ingress.tls }}
@@ -241,7 +277,7 @@ spec:
           name: "{{ template "app.chartname" . }}-configmap"
       - name: data-volume
         persistentVolumeClaim:
-          claimName: data-volume-claim
+          claimName: {{ template "app.chartname" . }}-data
       {{- range .Values.ingress.tls }}
       - name: {{ .secretName | replace "." "-" }}
         secret:
